tap "anomalyco/tap", trusted: true
tap "mongodb/brew", trusted: true

brew "cbonsai"
brew "coreutils"
brew "dnscrypt-proxy"
brew "icu4c@78"
brew "ffmpeg-full", link: true
brew "gnu-tar"
brew "imagemagick-full", link: true
brew "knot"
brew "mise"
brew "nmap"
brew "pigz"
brew "pkgconf"
brew "poppler"
brew "pv"
brew "sevenzip"
brew "tty-clock"
brew "mongodb/brew/mongodb-community@8.0"

cask "chatgpt"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "legcord"
cask "obsidian"
cask "orbstack"
cask "pearcleaner"
cask "raycast"
cask "rectangle"
cask "shottr"
cask "supacode"
cask "tailscale-app"
cask "telegram"
cask "vlc"
cask "yaak"
cask "zed"
cask "zen"

npm "corepack"
